name: flutter_2048
description: 2048 game using flutter
repository: https://github.com/lututui/2048_flutter

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.0.5
  path_provider: ^1.6.5
  async: ^2.4.0
  shared_preferences: ^0.5.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: false
  image_path: assets/icon/icon.png

flutter:
  uses-material-design: true

  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
          style: normal
